### ISSUE TITLE
Story explorer is not available in projects that use main.ts

### ISSUE THREAD

**Issue by yannbf** [joshbolduc/vscode-story-explorer#451]
First of all, congrats on this extension. I love it so much!!

Second, it took me a while to figure out why it wasn't working on my project. The `Story explorer` actions in the command palette won't appear in case projects do not use `.js` as an extension for `.storybook/main`.

So I wonder if:
1 - There could be a better way to surface this problem and help users understand how to fix it (maybe there is and I just missed it?)
2- Other extensions could be supported, such as `.ts`

Thank you!

**Comment by joshbolduc** [comment]
Thanks for the feedback!

I am a little surprised at the behavior you observed, since the activation events don't actually rely on `main.js` in particular. Instead they look for common stories file patterns or a `.storybook` directory: https://github.com/joshbolduc/vscode-story-explorer/blob/887ae1bbee6eb3d656904b186dd35f76ff34c970/package.json#L45-L50

I'm curious if you happened to debug the issue by, say, renaming `main.ts` to `main.js`? In that case it's possible the extension was activated because VS Code noticed a file matched `.storybook/*`, but that the specific extension wasn't a factor. This might have happened if the [initial workspace search timed out](https://code.visualstudio.com/updates/v1_63#_timeout-of-workspacecontains), which would've caused the extension not to be activated on load.

I think the fundamental issue is (as far as I can see) the extension can't do much to warn or advise users about the problem without being activated; if the extension doesn't get activated, it's basically invisible. So I think the likely resolution will be to be more aggressive about requesting activation, and relying on internal mechanisms to minimize runtime impact in projects that don't actually use Storybook.

(Incidentally, `main.js` _is_ hardcoded in a couple places, so I wouldn't expect story discovery to work out of the box anyway. But that doesn't sound like it's the issue you experienced. I would still expect commands in the command palette to appear, and the story panel should also appear with a hint to manually configure story globs. I'll need to explore how to load a `main.ts` file since it's the one thing that currently gets `require`d, so it'll break if there's any TypeScript syntax in the file.)

**Comment by joshbolduc** [comment]
Actually, I stand corrected--I just tried this myself and I am seeing the same behavior you described, and it's not actually activation-related like I had thought. I need to dig into what's happening, since it's not what I expected.

**Comment by joshbolduc** [comment]
Alright, I've figured out what was happening and [published some changes in v0.5.6](https://github.com/joshbolduc/vscode-story-explorer/releases/tag/v0.5.6) that should improve the behavior here:

- Configuration file extensions other than `.js` are now recognized. As mentioned above, there's no guarantee that they'll be parsed correctly (although this is already true of `main.js`). But they will at least be detected as valid.
- The stories pane now always appears. Previously, it would only appear if a config file were detected. This is less necessary now that detection is improved, but at this point I think it's more valuable to have it visible as a potential debugging aid (in case there's some misconfiguration) than to hide it in projects that really don't have stories.
- The messages that appear when stories haven't been loaded have been refined to be more precise. Coupled with keeping the stories pane visible, I think the calls to action here will be helpful (like setting stories globs explicitly via settings), especially if we can't read the configuration file directly for some reason.

Let me know how it works for you, and thanks again for the feedback.

**Comment by yannbf** [comment]
Wow thank you so much for such quick – very informational – response! I updated the extension and it's working perfectly!
